### ISSUE TITLE
Support multiple relays

### ISSUE THREAD

**Issue by AsaiToshiya** [theborakompanioni/nostr-action#159]

**Comment by theborakompanioni** [comment]
What about just splitting the `relay` var by `,`..?
This would preserve backward compatibility.

e.g.
```yml
uses: theborakompanioni/nostr-action@v1
with:
  key: ${{ secrets.NOSTR_KEY }}
  relay: wss://relayer.fiatjaf.com, wss://nostr-dev.wellorder.net, wss://relay.damus.io
  content: Hello World
```
